### ISSUE TITLE
Is there a way to isolate just the SaaS Cognito capabilities?

### ISSUE THREAD

**Issue by davidwhand** [aws-quickstart/saas-identity-cognito#6] opened 2017-12-15 02:26 UTC
Thank you for all the work in putting this Quickstart together.  It is awesome work!  I am trying to isolate just the SaaS Cognito capabilities.  I would like to combine the SaaS Cognito capabilities in this QuickStart with a serverless Lambda & DynamoDB application.  I really want to implement this QuickStart, https://aws.amazon.com/getting-started/serverless-web-app/, with the SaaS isolation model in this Github repository.  Any thoughts on the best approach to "combine" the SaaS isolation model with the serverless Lamda and DynamoDB from the other quickstart?

**Comment by ssaripal** [comment] 2017-12-19 02:54
I was exactly looking for same. I do have few concerns around stateless nature of lambda. What I understand is, we need to even more break up module into individual functions to comply to microservices best practices. 

Can you also suggest (or point me to) on how to perform testing on serverless. A quick start which shows end to end devOps process like this one would be invaluable with only true serverless architecture. github/CodeCommit (source/cloudformation/SAM)--> CodePipeline-->CodeBuild --> CodeDeploy

**Comment by judahb** [comment] 2017-12-19 17:16
Hi All,

We have been evaluating a Serverless version of this Quick Start. This must be prioritized internally. We will discuss in early 2018, and I will respond to this thread.

Thanks,
Judah

**Comment by davidwhand** [comment] 2017-12-24 19:36
Thanks Judah.  Let us know ASAP.  I am about to pay to have this built and I would prefer to wait a bit if I do not need to pay someone to learn how to implement it.

**Comment by judahb** [comment] 2018-04-02 19:30
RDS MySQL is not on the roadmap for this specific reference architecture.

**Comment by zavier-sanders** [comment] 2018-04-13 22:07
Hi, 

This is a really great Quickstart! Thank you for putting this together.

Are you guys still considering a Serverless version of this? 


Thanks,
Zavier

**Comment by davidwhand** [comment] 2018-04-16 12:35
Zavier,

I actually have a working version of this in an Express app running in
Lambda.  Not sure I will be able to open source it since I spent personal
money to get it developed.  In a few weeks we should have a more polished
version.  We are leveraging serverless.com to build and deploy the app in
AWS.

David

**Comment by judahb** [comment] 2018-04-16 16:28
@davidwhand Please connect with me on LinkedIn. It would be worthwhile for us to discuss.

Thanks,
Judah

**Comment by judahb** [comment] 2018-06-06 00:09
All,

Please provide a detailed list of enhancements and bug fixes you are interested in for a potential serverless version of this.

**Comment by jexh** [comment] 2018-08-07 13:12
I don't know about others but here is my wish list:
* Cognito for identity - shared cognito pool across all tenants, using groups, and roles to control data access. This offers a different example to the current quick-start.
* GraphQL backend using AppSync instead of a RESTful example. Use queries, mutators and subscriptions.
* Combination of Lambdas(various languages?) and direct DynamoDB access to implement resolvers.
* There should be an example of cross region shared data being used with subscriptions. Global DynamoDB tables should be used to show that a mutation received in one location causes an update with a subscription connected to another location.
* All wrapped up in a CloudFormation template.

**Comment by judahb** [comment] 2018-08-07 15:09
@jexh This is a great wish list. Note, everything below is subject to change prior to the serverless version releasing.

1.  A Shared Cognito User Pool across Tenants is considered in-scope for MVP1 for the Serverless Architecture, but at the current time Cognito User Pools is a per-region construct, which means this is isolated to a specific region. My current thoughts (open to feedback here), is to provide two types of Identity configurations based on Tiers. For "Free Tier" and "Standard Tier" I was going to configure a shared User Pool across Tenants in a single region, and for "Premium" or "Enterprise" Tier i was going to have the system provision a new User Pool per tenant. This allows the ISV to determine how to isolate the configuration based on the corresponding profile for the customer and isolation requirements. Does this approach sound interesting? (Want to make sure before i implement)
2. Initially, upon release of the Serverless SaaS Reference Architecture their are no plans to incorporate a GraphQL Backend with AWS AppSync, but since other customers have described interest a few times, I will do my best to assess the work effort to integrate it post go-live sometime in 1H 2019. I would need to see more interest here first, but its a great request.
3. Combination of Various Lambda Languages is a fair ask, but the goal here with serverless was to refactor the code for Serverless primarily upon initial release. That said, I see the technical value here, but I would need a use case for it that would require the development of brand new microservice or code. I will discuss this internally with the team before identifying an approach here. What language or framework would you be interested in here?
4. Cross Region was something I wanted to incorporate but that is a slippery slope from a compliance and security perspective, so I am thinking about taking an approach to allowing Login Across Supported Regions (of QuickStart) for the Initial Release, but where the customer needs to switch regions in a drop down similar to what is done in AWS and where data lives in a self contained region. I do not want data to cross region boundaries but for the purposes of this, I may have a global dynamodb table with hash map in which i have a hash for the username and a map to the User Pool ID. This work effort is being scoped and not necessarily included as their are a number of changes that would need to be made to accommodate. This is a stretch goal for initial release.

**Comment by jexh** [comment] 2018-08-07 15:27
@jodahb Thanks for the prompt update. All your suggestions/compromises make sense to me. It's a shame about AppSync as that integration with multi-tenancy is my main interest but I understand why. My reason for suggesting multi-language lambda implementations was just to provide an easy way to understand the source no matter the background. All the information required for implementing in your favourite supported language is already in the [getting started with Lambda guide.](https://aws.amazon.com/lambda/getting-started/).

**Comment by judahb** [comment] 2018-08-14 12:42
@jexh We are familiar with how to integrate various languages in Lambda and this is not the challenge. The issue is bandwidth for writing net new microservice code in a different language prior to this quickstarts release given the priority of this quickstart is serverless. What we need is technical requirements, business objective and use case, and the value for AWS. Can you provide more details on these?

**Comment by davidwhand** [comment] 2018-09-15 15:03
Benedek,

I have it built.  We are in beta mode at the moment.  You can create a
tenant at www.scheduleadr.com.  100% serverless leveraging Cognito, Lamdba,
DynamoDB, etc.

David

On Fri, Sep 14, 2018 at 8:22 PM, Benedek Kokenyesi <notifications@github.com

**Comment by judahb** [comment] 2018-09-21 18:04
@kbenedek Please reach out to your AWS Account team and sign a mutual NDA. Once thats in place i can provide more details.

**Comment by derektumulak** [comment] 2018-11-02 20:31
@judahb I'm interested in learning more about Serverless SaaS reference architecture as well. Do I still need to sign an NDA at this point and/or is there a URL with more information at this point?

Thanks!
-Derek

**Comment by jd0x** [comment] 2018-12-05 21:11
@judahb -  I am interested in the serverless SaaS reference architecture as well. What is the best way to contact you for this?

Platform looks great @davidwhand! If there are resources that helped along the way I'd appreciate any content you could share.

**Comment by jamesgraham** [comment] 2018-12-14 22:09
@judahb I'm echoing @derektumulak here but do we need to get an NDA in place prior to seeing v2 of this?

**Comment by davidwhand** [comment] 2018-12-16 16:51
Not sure what resources the developers used to build it.  I can put you in
touch with the developers if you'd like.

**Comment by derektumulak** [comment] 2018-12-27 23:21
I'd really like to get more guidance on how best to move toward a version of this that is serverless. I've reached out to the my AWS account team for more than a month and have had limited response.

Thanks,
-Derek

**Comment by derektumulak** [comment] 2019-02-23 15:09
@davidwhand I believe I'm looking for something similar to what you've done. Would you be able to point me in the direction of how you created https://www.scheduleadr.com/?

Thanks!
-Derek

**Comment by davidwhand** [comment] 2019-02-25 14:54
Derek,

We used a development firm to create it.  Feel free to contact me on
LinkedIn and I can point you in the right direction.

David

**Comment by derektumulak** [comment] 2019-02-25 14:59
Hi David, there are multiple David Hands on LinkedIn. Can you send me
specific information or reach out to me, Derek Tumulak, since my name is
unique.

Thanks!
-Derek

**Comment by judahb** [comment] 2019-03-04 20:44
The team has decided to take an alternate approach here. As of now, a true 1:1 version in serverless is no longer expected. That said, our team is working on a number of code projects that will demonstrate more advanced and deep concepts with alternative technologies such as serverless, relational databases, alternative frameworks, and container technologies. As a result, I will close this ticket, but will comment on it once we have additional content we can showcase that will highlight some of the asks in this thread.

**Closed by judahb** 2019-03-04 20:44 UTC
Labels: enhancement, help wanted

**Comment by nikzb** [comment] 2021-06-06 15:21
@judahb Do you have any recommendations on sample code projects from AWS that you described above that may help with implementing something like this with serverless technologies?
